# Generated by Django 5.1.7 on 2025-03-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='responder_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
